import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import SidebarMenu from "@/components/sidebar-menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { useSidebar } from "@/hooks/use-store";
import { cn } from "@/lib/utils";
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Sidebar />
          <SidebarMenu />
        </div>
        <div className="">{children}</div>
      </body>
    </html>
  );
}
